{
 "title": "Resolver",
 "time": { "from": "2023-10-31T09:47:24.302Z", "to": "2023-10-31T10:08:18.393Z" },
 "panels": [
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 5, "w": 22, "x": 0, "y": 1 },
   "options": {
    "content": "# TCP Connectivity\n\n- Pooled connections are connections that can be reused\n- Ephemeral connections are connections for one-time use\n- Ephemeral connections are generally opened if the pool is exhausted or as fallback mechanism"
   }
  },
  {
   "title": "TCP Connectivity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 6 },
   "targets": [
    { "expr": "client_tcp_dial_errors_total", "legendFormat": "Dial Errors {{instance}}" },
    {
     "expr": "client_tcp_conn_opened_total{type=\"pooled\"}",
     "legendFormat": "Pooled Opened {{instance}}"
    },
    {
     "expr": "client_tcp_conn_opened_total{type=\"ephemeral\"}",
     "legendFormat": "Ephemeral opened {{instance}}"
    }
   ]
  },
  {
   "title": "Open Pooled TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 6 },
   "targets": [
    {
     "expr": "client_tcp_conn_open{type=\"pooled\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open Ephemeral TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "client_tcp_conn_open{type=\"ephemeral\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Pool Exhaustion Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 15, "y": 6 },
   "targets": [
    { "expression": "$A / ($A+$B)", "type": "math" }
   ]
  },
  {
   "title": "Avg Queries per TCP conn",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($qv6 + $qv4) / ($ephopen + $poolopen)",
     "type": "math"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Resolved Domains",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(resolver_domains_resolved[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resolved Domains per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "rate(resolver_domains_resolved[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error Response Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (resolver_query_responses{isFinal=\"true\", hasErr=\"true\"})/sum by (instance) (resolver_query_responses{isFinal=\"true\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum (resolver_query_responses{isFinal=\"true\", hasErr=\"true\"})/sum (resolver_query_responses{isFinal=\"true\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "dns_cache_size", "legendFormat": "Size {{instance}}" },
    {
     "expr": "dns_cache_hits{}/(dns_cache_hits{}+dns_cache_misses{})",
     "legendFormat": "Hit Ratio {{instance}}"
    }
   ]
  },
  {
   "title": "Responses by Code",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(rcode) (resolver_query_responses{isFinal=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retries by Code",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(rcode) (resolver_query_responses{isFinal=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Infrastructure Cache Backoff Durations",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (infra_cache_backoff_duration_seconds_bucket)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Infrastructure Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "infra_cache_size", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Wire Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (client_queries_sent_total)",
     "legendFormat": "Sent {{instance}}"
    },
    {
     "expr": "sum by (instance) (rate(client_queries_sent_total[$__rate_interval]))",
     "legendFormat": "Rate {{instance}}"
    }
   ]
  },
  {
   "title": "Queries Inflight",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 42 },
   "targets": [
    { "expr": "client_queries_inflight", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Average RTT over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(client_queries_rtt_sum[$__rate_interval])\r\n/\r\nrate(client_queries_rtt_count[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query RTT",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le, job) (client_queries_rtt_bucket)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query RTT (node1)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le, job) (client_queries_rtt_bucket{instance=\"node01.dns-v6-scans.measurement.network:2112\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query RTT (node2)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le, job) (client_queries_rtt_bucket{instance=\"node02.dns-v6-scans.measurement.network:2112\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Rate Limiting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Rate Limiting by IP",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (client_ratelimiting_duration_seconds_bucket{type=\"inflight\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rate Limiting by Queries/Second",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (client_ratelimiting_duration_seconds_bucket{type=\"time\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rate Limiting by IP (node1)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (client_ratelimiting_duration_seconds_bucket{type=\"inflight\", instance=\"node01.dns-v6-scans.measurement.network:2112\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rate Limiting by Queries/Second (node1)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 10, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (client_ratelimiting_duration_seconds_bucket{type=\"time\", instance=\"node01.dns-v6-scans.measurement.network:2112\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rate Limiting by IP (node2)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (client_ratelimiting_duration_seconds_bucket{type=\"inflight\", instance=\"node02.dns-v6-scans.measurement.network:2112\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rate Limiting by Queries/Second (node2)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 10, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (client_ratelimiting_duration_seconds_bucket{type=\"time\", instance=\"node02.dns-v6-scans.measurement.network:2112\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rate Limiting by IP (node3)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (client_ratelimiting_duration_seconds_bucket{type=\"inflight\", instance=\"node03.dns-v6-scans.measurement.network:2112\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rate Limiting by Queries/Second (node3)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 10, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (client_ratelimiting_duration_seconds_bucket{type=\"time\", instance=\"node03.dns-v6-scans.measurement.network:2112\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rate Limiting by IP (node 4)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (client_ratelimiting_duration_seconds_bucket{type=\"inflight\", instance=\"node04.dns-v6-scans.measurement.network:2112\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rate Limiting by Queries/Second (node4)",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 10, "x": 10, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (client_ratelimiting_duration_seconds_bucket{type=\"time\", instance=\"node04.dns-v6-scans.measurement.network:2112\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Runtime and Debugging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Number Of Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 84 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory Consumption (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(go_memstats_alloc_bytes[$__interval]) / 1000 / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 84 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Domains currently being resolved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 84 },
   "targets": [
    { "expr": "resolver_domains_resolving", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Batches currently being resolved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 84 },
   "targets": [
    { "expr": "resolver_batches_resolving", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}