# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protobuf_model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dprotobuf/protobuf_model.proto\x12\x02io\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x01\n\nResolution\x12\x0f\n\x07\x64omains\x18\x01 \x03(\t\x12-\n\tstartTime\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x64uration\x18\x03 \x01(\x03\x12\x1a\n\x08zoneData\x18\x04 \x01(\x0b\x32\x08.io.Zone\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x0b\n\x03idx\x18\x06 \x03(\x04\"U\n\x04Zone\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1a\n\x08subZones\x18\x02 \x03(\x0b\x32\x08.io.Zone\x12#\n\x0bnameServers\x18\x03 \x03(\x0b\x32\x0e.io.NameServer\"/\n\nNameServer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bipAddresses\x18\x02 \x03(\t\"\xc1\x01\n\x0fMessageExchange\x12&\n\x10originalQuestion\x18\x01 \x01(\x0b\x32\x0c.io.Question\x12\x14\n\x0cresponseAddr\x18\x02 \x01(\t\x12\x14\n\x0cnameServerIp\x18\x03 \x01(\t\x12\x1e\n\x08metadata\x18\x04 \x01(\x0b\x32\x0c.io.Metadata\x12\x0f\n\x07message\x18\x05 \x01(\x0c\x12\x15\n\rerror_message\x18\x06 \x01(\t\x12\x12\n\nerror_code\x18\x07 \x01(\t\"5\n\x08Question\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\r\x12\r\n\x05\x63lass\x18\x03 \x01(\r\"\xf5\x01\n\x08Metadata\x12\x11\n\tfromCache\x18\x01 \x01(\x08\x12\x10\n\x08retryIdx\x18\x02 \x01(\r\x12\x0e\n\x06\x63onnId\x18\x03 \x01(\x0c\x12\x0b\n\x03tcp\x18\x04 \x01(\x08\x12\x15\n\rcorrelationId\x18\x05 \x01(\x0c\x12\x10\n\x08parentId\x18\x06 \x01(\x0c\x12/\n\x0b\x65nqueueTime\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0b\x64\x65queueTime\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07isFinal\x18\t \x01(\x08\x12\x0b\n\x03rtt\x18\n \x01(\x03\x42\x0bZ\t/protobufb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.protobuf_model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\t/protobuf'
  _RESOLUTION._serialized_start=71
  _RESOLUTION._serialized_end=220
  _ZONE._serialized_start=222
  _ZONE._serialized_end=307
  _NAMESERVER._serialized_start=309
  _NAMESERVER._serialized_end=356
  _MESSAGEEXCHANGE._serialized_start=359
  _MESSAGEEXCHANGE._serialized_end=552
  _QUESTION._serialized_start=554
  _QUESTION._serialized_end=607
  _METADATA._serialized_start=610
  _METADATA._serialized_end=855
# @@protoc_insertion_point(module_scope)
